// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBupS8gc4Fz04SmGYbKCGxcc0MU3NDze1c',
    appId: '1:758763526828:android:b37e841758c7e92b45dd09',
    messagingSenderId: '758763526828',
    projectId: 'shuqair-portfolio',
    storageBucket: 'shuqair-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNozmmlKmghNXmymSVUgMIQj0mHH4dpc4',
    appId: '1:758763526828:ios:f643865b545176b045dd09',
    messagingSenderId: '758763526828',
    projectId: 'shuqair-portfolio',
    storageBucket: 'shuqair-portfolio.firebasestorage.app',
    androidClientId: '758763526828-oa12fks9i05l92l6r4pu9b485s55ikor.apps.googleusercontent.com',
    iosClientId: '758763526828-ccap5m0156ds25b5vvhq4175lvvmi2sb.apps.googleusercontent.com',
    iosBundleId: 'com.chatAppFirebaseExample',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDulg7szIAay5VbfXc3xXBr0gl1dnNnE',
    appId: '1:758763526828:web:fb865ffd62e819b345dd09',
    messagingSenderId: '758763526828',
    projectId: 'shuqair-portfolio',
    authDomain: 'shuqair-portfolio.firebaseapp.com',
    storageBucket: 'shuqair-portfolio.firebasestorage.app',
  );

}